### PR TITLE
Added tools for automated documentation with Sphinx and Numpydoc

### PR DESCRIPTION
**Pull request by nickstanisha**
I've added a docs directory containing the necessary scripts and tools to make some simple automated documentation using [Sphinx](http://www.sphinx-doc.org/en/stable/).  I've also changed the docstrings to use the Numpy style so that the automated documentation can be presented in the nice format provided by [Numpydoc](https://pypi.python.org/pypi/numpydoc). In addition to the nice formatting, Sphinx also provides tools for searching and browsing the documenation.

Moving forward, you could decide to follow [these](https://pages.github.com/) directions and host your documentation on Github directly, which I've done here: https://nickstanisha.github.io/BigQuery-Python/ by creating a gh-pages branch of my [fork](https://github.com/nickstanisha/BigQuery-Python).

The content of the documentation stayed the same, the only change was the formatting.  Additionally, no code was changed so all tests are still passing.

### CODE REVIEW

**Comment by tylertreat** [comment]
Thanks! I will try to get the docs hosted soon.

**Comment by nickstanisha** [comment]
No problem! Thanks for the merge!

**Comment by tylertreat** [comment]
@nickstanisha I pushed the docs to the gh-pages branch. Any idea why some files are 404'ing despite being in the branch? http://tylertreat.github.io/BigQuery-Python/

**Comment by nickstanisha** [comment]
@tylertreat I don't see any 404-ing casually browsing through the docs.  Try adding a blank [.nojekyll file](https://github.com/blog/572-bypassing-jekyll-on-github-pages) at the top directory of your branch to prevent GitHub pages from processing the HTML with Jekyll. That should make everything behave like you'd expect.

**Comment by tylertreat** [comment]
That did the trick, thanks!

**Pull request merged**
