### PR TITLE
Updated library and unit tests to run on Python 2 and Python 3

### PR DESCRIPTION
**Pull request by blarghmatey**

### CODE REVIEW

**Comment by tylertreat** [comment]
Awesome! I wonder if we can configure Travis CI to run tests with both python 2 and 3?

**Comment by blarghmatey** [comment]
I know that if we add Tox then it's possible to specify multiple versions and flavors of Python for Travis to run. https://www.dominicrodger.com/tox-and-travis.html

**Comment by tylertreat** [comment]
I would definitely be in favor of adding that.

**Comment by blarghmatey** [comment]
@tylertreat I added tox to the test config as well as adding in a patch of the pull request #29. This should be ready for review now.

**Comment by tylertreat** [comment]
Thanks!

**Pull request merged**
